appName: tag-worker
appPort: 9199
product: tag
hpa_mem: false
image:
  registry: registry.trigger.services
  repository: tag
  pullPolicy: Always
scale:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
