{{- $global_data := .Values.global }}
{{- $tag_data := $global_data.tag_back }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.global.product }}
    tier: {{ .Values.appName }}
spec:
  {{- if $tag_data.autoscaling.enabled }}
  replicas: {{ $tag_data.autoscaling.minReplicas }}
  {{- else }}
  replicas: {{ .Values.scale.minReplicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
{{- with $global_data.deploymentStrategy }}
  strategy:
{{ toYaml . | trim | indent 4 }}
{{- end }}
    {{- if eq $global_data.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    {{- end }}
  template:
    metadata:
      annotations:
        {{- include "tag-back.annotations" . | nindent 4 }}
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if not (eq $global_data.repotype "public") }}
      imagePullSecrets:
        - name: {{ $global_data.imagePullSecrets.name }}
      {{- end }}
      securityContext:
        {{- toYaml $tag_data.podSecurityContext | nindent 8 }}
      initContainers:
        {{- include "InitWait.postgres" . | nindent 8 }}
      containers:
        - name: {{ .Values.appName }}
          securityContext: {{- toYaml $tag_data.securityContext | nindent 12 }}
          image: {{ include "tag-back.imageUrl" . | quote }}
          resources:
            {{- toYaml $tag_data.resources | nindent 12 }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | default "IfNotPresent" }}
          ports:
          - containerPort: {{ .Values.appPort }}
          env:
            - name: LOG_LEVEL
              value: "{{ .Values.global.tag_back.config.log_level }}"
            - name: CAPTHA_AUTH
              value: "{{ .Values.global.tag_back.config.capchaauth }}"
            - name: CACHE_ACTIVE
              value: "{{ .Values.global.tag_back.config.capchaactive }}"
            - name: CAPTHA_SECRET
              value: "{{ .Values.global.tag_back.config.capchasecret }}"
            - name: CONNECT_LIMIT
              value: "{{ .Values.global.tag_back.config.connect_limit }}"
            - name: LOG_EXT
              value: "{{ .Values.global.tag_back.config.logext }}"
            - name: JS_ENABLE
              value: "{{ .Values.global.tag_back.config.js_enable }}"
            - name: OUT_POOL_SIZE
              value: "{{ .Values.global.tag_back.config.out_pool_size }}"
            - name: JS_LIBS
              value: "{{ .Values.global.tag_back.config.js_libs }}"
            - name: JS_STATEMENTS_LIMIT
              value: "{{ .Values.global.tag_back.config.js_statements_limit }}"
            - name: JS_MAX_REQUESTS_PER_CONTEXT
              value: "{{ .Values.global.tag_back.config.js_max_requests_per_context }}"
            - name: SMTP_KEY
              value: "{{ .Values.global.tag_back.config.smtp_key }}"
            - name: GPT_TOKEN
              value: "{{ .Values.global.tag_back.config.gpt_token }}"
            - name: GPT_ORG
              value: "{{ .Values.global.tag_back.config.gpt_org }}"
            - name: GROUP_LIMITS
              value: "{{ .Values.global.tag_back.config.group_limits }}"
            - name: GROUP_LIMITS_TIME
              value: "{{ .Values.global.tag_back.config.group_limits_time }}"
            - name: MAIL_SCRIPT
              value: "{{ .Values.global.tag_back.config.mail_script }}"
            - name: WS_MAX_MESSAGE_TTL
              value: "{{ .Values.global.tag_back.config.ws_max_message_ttl | default 2592000 }}"
            - name: WS_MAX_QUEUE_SIZE
              value: "{{ .Values.global.tag_back.config.ws_max_queue_size | default 1000 }}"
            - name: PORT
              value: "{{ .Values.appPort }}"
            - name: LIC_SERVER
              value: "tag-license-service:8585"
            - name: FRONT_URL
              value: "https://{{ .Values.global.subdomain}}.{{ .Values.global.domain }}"
            - name: REG_ALLOWED
              value: "{{ .Values.global.tag_back.config.reg_allowed }}"
            {{- include "tag_env_db" . | nindent 12 }}
            {{- include "tag_env_timescale" . | nindent 12 }}
            {{- include "tag_env_redis" . | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.appPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.appPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
