appName: tag-license
appPort: 8585
product: tag
image:
  registry: registry.trigger.services
  repository: tag
  pullPolicy: Always
scale:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
