{{- if not .Values.global.tag_license.existingLicenseSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tag_license.licenseSecretName | default "tag-license" }}
type: Opaque
data:
  {{- $root := . -}}
  {{- range $path, $bytes := .Files.Glob "license/license.key" }}
  license.key: '{{ $root.Files.Get $path | b64enc }}'
  {{- end }}
{{- end -}}