{{- if .Values.global.timescale.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tag.timescaleSecretName" . | quote }}
  labels:
    {{- include "tag.labels" . | nindent 4 }}
    tier: "postgres"
type: Opaque
data:
  {{- range $key, $value := .Values.global.timescale.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end}}
